### ISSUE TITLE
没有用呀兄弟

### ISSUE THREAD

**Issue by coco-w** [Curtion/HearthStone-AutoReConn#1]
下着试了下没用

**Comment by Curtion** [comment]
> 下着试了下没用

额，由于没有日志我只能简单说明一下程序启动前要条件：
1. hsarec.exe和hsarec.ico保证在同一层目录中，不可缺少
2. 防火墙处于开启状态
3. 炉石正在运行
4. 管理员权限运行程序
5. windows10系统

无法使用分为两种情况：
(一) 右键托盘中选项和快捷键都失效：
大概率是上述原因导致的

(二) 快捷键失效，但是托盘拔线功能有效：
这种可能是热键被占用，或者重启应用生效。

不清楚你是哪种情况？ 还请看一下防火墙的出站规则中有没有一条叫做Curtion_LS的规则，其中的炉石应用路径是否正确。

本来以为没人会用，但是既然有人在用了，接下来会把一些异常处理和运行日志加上。

**Comment by ACui96** [comment]
我这也不好使，满足上面的条件 快捷键和托盘都不能使。

**Comment by Curtion** [comment]
经过我不懈的努力，准备完善该程序。最终拖到了整活被砍的那一天，这个软件不会再更新，再见朋友们！

**Comment by Curtion** [comment]
忘记了还有电表需要拔线，先开着吧，接着弄

**Comment by Curtion** [comment]
添加了日志功能，如果使用失效可上传日志反馈。
https://github.com/Curtion/HearthStone-AutoReConn/releases/tag/v0.2.0
