### ISSUE TITLE
判断防火墙规则是否存在结束:false       请问true和false分别代表什么意思

### ISSUE THREAD

**Issue by JasonBourne33** [Curtion/HearthStone-AutoReConn#2]
01:02:30 [INFO] 开始判断防火墙规则是否存在
01:02:30 [INFO] 判断防火墙规则是否存在结束:false
01:02:32 [INFO] 开始判断防火墙规则是否存在
01:02:32 [INFO] 判断防火墙规则是否存在结束:false
01:02:32 [INFO] 开始获取炉石路径
01:02:33 [INFO] 炉石路径获取成功:[]
01:03:08 [INFO] 开始判断防火墙规则是否存在
01:03:08 [INFO] 判断防火墙规则是否存在结束:false
01:03:08 [INFO] 开始获取炉石路径
01:03:09 [INFO] 炉石路径获取成功:[]

**Comment by Curtion** [comment]
false代表没有找到防火墙规则。

程序的流程是：
先查询是否已经创建防火墙规则(该规则作用是对炉石断网)
如果查询到则直接启用该规则，3秒后再禁用该规则。
否则先会创建防火墙规则，再进行上述操作。

日志看起来是没有找到炉石的进程，或者是因为其它原因导致根据炉石进程没有找到路径。

**Comment by Curtion** [comment]
先关闭issues，如果有疑问可以再次打开
